FROM ubuntu:16.04
MAINTAINER Stefano Verhoeve stefanoverhoeve44@gmail.com
RUN apt-get update
RUN apt-get update
RUN apt-get upgrade -y
RUN mkdir -p /rekeningrijdenverplaatsingsmodule
WORKDIR /rekeningrijdenverplaatsingsmodule
COPY . .